---
# Any specific customization required in the vagrant environment needs to be
# done in this play
- name: Pre-deploy bootstrapping
  hosts: all
  become: true
  gather_facts: false
  tags:
    - predeploy
  vars:
    kmods:
      - dm_mirror
      - dm_snapshot
      - dm_thin_pool

  tasks:
    - name: Extend root VG
      lvg:
        vg: atomicos
        pvs: /dev/vda2,/dev/vdb
        state: present

    - name: Extend the root LV and FS to occupy remaining space
      lvol:
        vg: atomicos
        lv: root
        size: 100%FREE
        resizefs: true
      tags: diskextend

    - name: Load required kernel modules
      modprobe:
        name: "{{ item }}"
        state: present
      with_items: "{{ kmods }}"

    - name: Persist loaded modules
      copy:
        dest: "/etc/modules-load.d/gluster-{{ item }}.conf"
        content: "{{ item }}"
      with_items: "{{ kmods }}"

    - name: Install packages
      command: "rpm-ostree install {{ item }}"
      with_items:
        # socat is needed for Helm
        - socat
        - ipvsadm

    - name: Reboot to make layered packages available
      shell: sleep 2 && systemctl reboot
      async: 1
      poll: 0

    - name: Wait for host to be available
      wait_for_connection:
        delay: 15

    # Required for alternate etcd deployment
    - name: Prepare for external-provisioner
      block:
        - name: Create /var/mnt/disks/vol[1..4] for local-storage
          file:
            path: '/var/mnt/disks/{{ item }}'
            state: directory
            owner: root
            group: root
            mode: 0700
          loop:
            - vol1
            - vol2
            - vol3
            - vol4
          tags:
            - external-provisioner

        - name: Create /var/mnt/vol[1..4] for local-storage
          file:
            path: '/var/mnt/{{ item }}'
            state: directory
            owner: root
            group: root
            mode: 0700
          loop:
            - vol1
            - vol2
            - vol3
            - vol4

        - name: Bind mount /var/mnt/vol[1..4] to /var/mnt/disks/vol[1..4]
          mount:
            src: '/var/mnt/{{ item }}'
            path: '/var/mnt/disks/{{ item }}'
            state: mounted
            fstype: none
            opts: bind
          loop:
            - vol1
            - vol2
            - vol3
            - vol4
      tags:
        - external-provisioner


- import_playbook: "./deploy-k8s.yml"
  vars:
    # local_release_dir needs to be set for atomic hosts.
    local_release_dir: "/var/vagrant/temp"
    # Required for alternate etcd deployment
    kube_hostpath_dynamic_provisioner: true
    local_volume_provisioner_storage_classes:
      - name: "local-storage"
        host_dir: "/var/mnt/disks"
        mount_dir: "/var/mnt/disks"

- import_playbook: "./deploy-gcs.yml"
